Update project0.md
cmsc330fall23/cmsc330fall23 pull request #3
Opened 2023-08-29 20:15 UTC by PickleNik

- fixes an issue with `brew` on M1/M2 macs by adding brew to PATH

2023-08-29 20:16 UTC, amalik03 commented
it helped thanks!

2023-08-31 02:39 UTC, PickleNik commented
it's so jover

2023-09-01 15:58 UTC, AndersSpear requested changes
bro this doesnt persist

2023-09-01 16:03 UTC, PickleNik commented
> bro this doesnt persist

fixd

2023-09-01 18:39 UTC, PickleNik commented
@AndersSpear bro pls merg cmon

2023-09-02 18:20 UTC, PickleNik commented
closing as stale

2023-09-02 18:20 UTC, closed without merging